### PR TITLE
Tape tests

### PR DESCRIPTION
**Pull request by vgenev**
Changed the Testing framework from Mocha to Tape and extended the unit tests to improve coverage

### CODE REVIEW

**Comment by ggrg** [comment]
Also, please add to README.md, the exports required for successful build (provided by @rmothilal)
```
export CPPFLAGS=-I/usr/local/opt/openssl/include
export LDFLAGS=-L/usr/local/opt/openssl/lib
```

**Comment by vgenev** [comment]
> @vgenev, thanks for adding the unit tests. I have the following comments:
> 
> * PR is not linked to a story
> * PR doesn't have description either
> * please, try to use feature/ branches on your fork in future
> * src/lib/kafka/consumer.js is not fully covered by tests. Do you intend to add more tests for that purpose? Also, for that lib script probably there are some tests in central-ledger/settlement which might be reused, aren't there?
>   Other than that, PR looks good and tests pass, thus I'd be happy to approve once you confirm the above.

* I am not seeing sometimes the field for linking to story, sometimes it doesn't give the story even when I type the story number. Its acting strange..
* I have added description
* central-settlement is using older consumer code. I think I got that one from central-ledger, but still are some differences. For that particular uncovered line in consumer.js, I will cover it. If you are referring to the lib/utils - I can check whats in the other repos and improve coverage later.

**Comment by ggrg** [comment]
Hi Valentin, thanks for adding to this PR. I see you have moved away from mocha in favour of tape. But I fail to receive 100% coverage on my side. Not sure how do you get it?
### Issue No. 1
 Please, add the following line to **package.json** right after test:coverage:
```
 "test:coverage-check": "npm run test:coverage && istanbul check-coverage"
```
Then create new file: **${workspaceFolder}/.istanbul.yml* with the following content:
```
instrumentation:
  include-all-sources: true
  excludes: []
check:
  global:
    statements: 90
    lines: 90
    branches: 90
    functions: 90
  each:
    statements: 90
    lines: 90
    branches: 90
    functions: 90
```
At last, you should run the following command: `npm run test:coverage-check`
Here I'm getting:
```
=============================== Coverage summary ===============================
Statements   : 91.12% ( 195/214 )
Branches     : 85.71% ( 30/35 )
Functions    : 83.33% ( 25/30 )
Lines        : 91.87% ( 192/209 )
================================================================================

1..35
# tests 35
# pass  35

# ok

ERROR: Coverage for branches (85.71%) does not meet global threshold (90%)
ERROR: Coverage for functions (83.33%) does not meet global threshold (90%)
ERROR: Coverage for branches (83.33%) does not meet per-file (/Users/georgi/mb/mojaloop/email-notifier/src/lib/utility.js)  threshold (90%)
ERROR: Coverage for statements (67.74%) does not meet per-file (/Users/georgi/mb/mojaloop/email-notifier/src/setup.js)  threshold (90%)
ERROR: Coverage for branches (0%) does not meet per-file (/Users/georgi/mb/mojaloop/email-notifier/src/setup.js)  threshold (90%)
ERROR: Coverage for lines (72.41%) does not meet per-file (/Users/georgi/mb/mojaloop/email-notifier/src/setup.js)  threshold (90%)
ERROR: Coverage for functions (16.67%) does not meet per-file (/Users/georgi/mb/mojaloop/email-notifier/src/setup.js)  threshold (90%)
ERROR: Coverage for statements (0%) does not meet per-file (/Users/georgi/mb/mojaloop/email-notifier/app.js)  threshold (90%)
ERROR: Coverage for lines (0%) does not meet per-file (/Users/georgi/mb/mojaloop/email-notifier/app.js)  threshold (90%)
```
If making 100% is too much for this story/PR, please at least add up to 90% in order to get rid of the errors.
### Issue No. 2
Also, there is something wrong with your .circleci setup. In the CI pipeline I can only see `ci/circleci: setup — Your tests passed on CircleCI!`. We should be having at least unit tests and coverage-check there as well.
### Issue No. 3
Last, but not least - please address my previous comment on README.md regarding the long error output you added (which also exposes some non-generic paths - `/Users/georgi/...`, which I find odd)

**Comment by elnyry** [comment]
@ggrg @rmothilal @mdebarros Regarding coverage, can we update it just for this component to 83% for this for an initial commit, to merge it, have a few runs on CI etc and then revisit it to make it >90% ?

**Pull request merged**
